### ISSUE TITLE
Change Math.random to time-based ID

### ISSUE THREAD

**Issue by igorsantana** [igorsantana/genetic-worms#2]
If the population grows enough, the`generateId`  function may not generate unique ids. Changing it to a time-based id generation can improve this.

**Comment by ferfabricio** [comment]
Se usar o uuid v1 para gerar o ID?
É time based e documentado por na RFC 4122
Tem um package no npm também
https://www.npmjs.com/package/uuid

**Comment by ferfabricio** [comment]
Se usar o uuid v1 para gerar o ID?
É time based e documentado por na RFC 4122
Tem um package no npm também
https://www.npmjs.com/package/uuid

**Comment by ferfabricio** [comment]
What you think about use uuid v1?

It's timestamp based and documented on RFC4122.
Have a npm package with compatibility in most of browsers.
https://www.npmjs.com/package/uuid

**Comment by igorsantana** [comment]
i've looked into the lib and it has no dependencies. i think i'm gonna implement it. if it had lots of dependencies i think i would build something.
